const jumps = [
{number: '515', type: 'night jump', location:'perris'},
{number: '516', type: 'freefly', location:'perris'},
{number: '517', type: 'belly', location:'perris'},
{number: '518', type: 'belly', location:'perris'},
{number: '519', type: '4way', location:'mile hi'},
{number: '520', type: '4way', location:'mile hi'},
{number: '521', type: '4way', location:'mile hi'},
{number: '522', type: 'coach', location:'mile hi'},
{number: '523', type: 'freefl', location:'mile hi'},
{number: '524', type: 'freefly', location:'mile hi'},
{number: '525', type: 'belly', location:'sebastian'},
{number: '526', type: 'belly', location:'sebastian'},
{number: '527', type: 'belly', location:'sebastian'},
{number: '528', type: 'wsln', location:'sebastian'},
{number: '529', type: 'wsln', location:'sebastian'},
{number: '530', type: 'wsln', location:'sebastian'},
{number: '531', type: 'wsln', location:'sebastian'},
{number: '532', type: 'wsln', location:'sebastian'},
{number: '533', type: 'wsln', location:'sebastian'},
{number: '534', type: 'wsln', location:'sebastian'},
{number: '535', type: 'wsln', location:'sebastian'},
{number: '536', type: 'coach', location:'mile hi'},
{number: '537', type: 'belly', location:'mile hi'},
{number: '538', type: 'coach', location:'mile hi'},
{number: '539', type: 'coach', location:'mile hi'},
{number: '540', type: 'coach', location:'mile hi'},
{number: '541', type: 'hop n pop', location:'mile hi'},
{number: '542', type: 'hop n pop', location:'mile hi'},
{number: '543', type: 'hop n pop', location:'mile hi'},
{number: '544', type: 'hop n pop', location:'mile hi'},
{number: '545', type: 'hop n pop', location:'mile hi'},
]

module.exports = jumps
